name: gtest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S . -B build && cmake --build build
    - name: make
      run: cd build && make test
