name: gtest

on: [push, pull_request]

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: configure
      run: cmake -S . -B build && cmake --build build
    - name: make
      run: cd build && make test
  coverage_report:
    name: Generate coverage report
    needs: gtest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # ... Generate LCOV files or download it from a different job
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: bartosz347/github-actions-report-lcov@06c2e5e945187378cbb1020c0d0edeb303f43857
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}